name: KitsPlus2
main: me.tlwv2.kitsp2.Main
version: 2.0
commands:
  createkit:
    description: Creates a kit
    usage: /createkit <name>
  deletekit:
    description: Deletes a kit
    usage: /deletekit <name>
  editkit:
    description: Edits a kit
    usage: /editkit <name> <inventory:effects:icon>
  kitgui:
    description: Opens Kit GUI
    usage: /kitgui
  editkitgui:
    description: Edit Kit GUI
    usage: /editkitgui